export const LOAD_CURRENCY_LIST_START = "LOAD_CURRENCY_LIST_START";
export const LOAD_CURRENCY_LIST_SUCCESS = "LOAD_CURRENCY_LIST_SUCCESS";
export const LOAD_CURRENCY_LIST_ERROR = "LOAD_CURRENCY_LIST_ERROR";

export const CONVERT_CURRENCY_LIST_START = "CONVERT_CURRENCY_LIST_START";
export const CONVERT_CURRENCY_LIST_SUCCESS = "CONVERT_CURRENCY_LIST_SUCCESS";
export const CONVERT_CURRENCY_LIST_ERROR = "CONVERT_CURRENCY_LIST_ERROR";
